[[]]
click_time = 2.3175982499999996
speed = "Slow"
direction = "Up"

[[]]
click_time = 2.8168352500000005
speed = "Slow"
direction = "Down"

[[]]
click_time = 3.331468416
speed = "Slow"
direction = "Left"

[[]]
click_time = 4.334267833
speed = "Slow"
direction = "Up"

[[]]
click_time = 4.847969458
speed = "Slow"
direction = "Down"

[[]]
click_time = 5.369293291
speed = "Slow"
direction = "Right"

[[]]
click_time = 6.373131582999999
speed = "Slow"
direction = "Left"

[[]]
click_time = 6.908272415999999
speed = "Slow"
direction = "Right"

[[]]
click_time = 7.356555125
speed = "Slow"
direction = "Left"

[[]]
click_time = 7.877960957999999
speed = "Slow"
direction = "Left"

[[]]
click_time = 8.081888791
speed = "Slow"
direction = "Down"

[[]]
click_time = 8.37515
speed = "Slow"
direction = "Right"

[[]]
click_time = 8.864734083
speed = "Slow"
direction = "Up"

[[]]
click_time = 9.375304791
speed = "Slow"
direction = "Left"

[[]]
click_time = 10.139601416
speed = "Slow"
direction = "Down"

[[]]
click_time = 10.417372875
speed = "Slow"
direction = "Left"

[[]]
click_time = 10.900359208
speed = "Slow"
direction = "Down"

[[]]
click_time = 11.406177875000001
speed = "Slow"
direction = "Left"

[[]]
click_time = 12.189693666
speed = "Slow"
direction = "Up"

[[]]
click_time = 12.45641825
speed = "Slow"
direction = "Right"

[[]]
click_time = 12.98322675
speed = "Slow"
direction = "Up"

[[]]
click_time = 13.474722415999999
speed = "Slow"
direction = "Right"

[[]]
click_time = 14.51637525
speed = "Slow"
direction = "Left"

[[]]
click_time = 14.550068290999999
speed = "Slow"
direction = "Right"

[[]]
click_time = 15.499684040999998
speed = "Slow"
direction = "Left"

[[]]
click_time = 15.499684040999998
speed = "Slow"
direction = "Right"

[[]]
click_time = 16.532894375
speed = "Slow"
direction = "Up"

[[]]
click_time = 16.92431275
speed = "Slow"
direction = "Down"

[[]]
click_time = 17.281808541
speed = "Slow"
direction = "Up"

[[]]
click_time = 18.558056333
speed = "Slow"
direction = "Right"

[[]]
click_time = 18.96643975
speed = "Slow"
direction = "Left"

[[]]
click_time = 19.381344875
speed = "Slow"
direction = "Right"

[[]]
click_time = 20.608449958
speed = "Slow"
direction = "Down"

[[]]
click_time = 20.985870291
speed = "Slow"
direction = "Left"

[[]]
click_time = 21.397920791
speed = "Slow"
direction = "Up"

[[]]
click_time = 22.6073885
speed = "Slow"
direction = "Down"

[[]]
click_time = 22.999769958
speed = "Slow"
direction = "Right"

[[]]
click_time = 23.406445375
speed = "Slow"
direction = "Up"

[[]]
click_time = 24.667498625
speed = "Slow"
direction = "Left"

[[]]
click_time = 25.016183541
speed = "Slow"
direction = "Down"

[[]]
click_time = 25.475579291
speed = "Slow"
direction = "Right"

[[]]
click_time = 25.883938208
speed = "Slow"
direction = "Up"

[[]]
click_time = 26.706343416
speed = "Slow"
direction = "Left"

[[]]
click_time = 27.098048125
speed = "Slow"
direction = "Down"

[[]]
click_time = 27.472990625
speed = "Slow"
direction = "Right"

[[]]
click_time = 27.858607083
speed = "Slow"
direction = "Up"

[[]]
click_time = 28.747877166
speed = "Slow"
direction = "Right"

[[]]
click_time = 29.306316957999996
speed = "Slow"
direction = "Left"

[[]]
click_time = 29.783588125
speed = "Slow"
direction = "Right"

[[]]
click_time = 30.256310790999997
speed = "Slow"
direction = "Left"

[[]]
click_time = 30.799635166
speed = "Slow"
direction = "Up"

[[]]
click_time = 30.799635166
speed = "Slow"
direction = "Left"

[[]]
click_time = 31.292033458
speed = "Slow"
direction = "Up"

[[]]
click_time = 31.292033458
speed = "Slow"
direction = "Left"

[[]]
click_time = 31.783108
speed = "Slow"
direction = "Down"

[[]]
click_time = 31.783108
speed = "Slow"
direction = "Right"

[[]]
click_time = 32.317180125
speed = "Slow"
direction = "Down"

[[]]
click_time = 32.349788416
speed = "Slow"
direction = "Right"

[[]]
click_time = 32.86467025
speed = "Slow"
direction = "Right"

[[]]
click_time = 33.247790958
speed = "Slow"
direction = "Left"

[[]]
click_time = 33.624475833
speed = "Slow"
direction = "Right"

[[]]
click_time = 33.96542925
speed = "Slow"
direction = "Left"

[[]]
click_time = 34.34829475
speed = "Slow"
direction = "Right"

[[]]
click_time = 34.608258625
speed = "Slow"
direction = "Left"

[[]]
click_time = 34.858538833
speed = "Slow"
direction = "Up"

[[]]
click_time = 35.232435958
speed = "Slow"
direction = "Down"

[[]]
click_time = 35.614906375
speed = "Slow"
direction = "Up"

[[]]
click_time = 35.983285833
speed = "Slow"
direction = "Down"

[[]]
click_time = 36.340067833
speed = "Slow"
direction = "Up"

[[]]
click_time = 36.63977
speed = "Slow"
direction = "Left"

[[]]
click_time = 36.7729695
speed = "Slow"
direction = "Right"

[[]]
click_time = 36.881253291
speed = "Slow"
direction = "Up"

[[]]
click_time = 37.298042875
speed = "Slow"
direction = "Left"

[[]]
click_time = 37.641336291
speed = "Slow"
direction = "Right"

[[]]
click_time = 38.014690125
speed = "Slow"
direction = "Left"

[[]]
click_time = 38.43973975
speed = "Slow"
direction = "Right"

[[]]
click_time = 38.631518458
speed = "Slow"
direction = "Up"

[[]]
click_time = 38.923341875
speed = "Slow"
direction = "Down"

[[]]
click_time = 39.275103041
speed = "Slow"
direction = "Left"

[[]]
click_time = 39.656388541
speed = "Slow"
direction = "Right"

[[]]
click_time = 40.0479065
speed = "Slow"
direction = "Up"

[[]]
click_time = 40.464654166
speed = "Slow"
direction = "Left"

[[]]
click_time = 40.564671708
speed = "Slow"
direction = "Down"

[[]]
click_time = 40.70848
speed = "Slow"
direction = "Right"

[[]]
click_time = 40.856200458
speed = "Slow"
direction = "Up"

[[]]
click_time = 40.948014
speed = "Slow"
direction = "Left"

[[]]
click_time = 41.348043375
speed = "Slow"
direction = "Down"

[[]]
click_time = 41.71603575
speed = "Slow"
direction = "Right"

[[]]
click_time = 42.123759291
speed = "Slow"
direction = "Up"

[[]]
click_time = 42.499096666
speed = "Slow"
direction = "Down"

[[]]
click_time = 42.740046416
speed = "Slow"
direction = "Right"

[[]]
click_time = 43.006452625
speed = "Slow"
direction = "Up"

[[]]
click_time = 43.3727695
speed = "Slow"
direction = "Left"

[[]]
click_time = 43.772963416
speed = "Slow"
direction = "Right"

[[]]
click_time = 44.149971083
speed = "Slow"
direction = "Left"

[[]]
click_time = 44.51456325
speed = "Slow"
direction = "Right"

[[]]
click_time = 44.715305375
speed = "Slow"
direction = "Up"

[[]]
click_time = 44.889930666
speed = "Slow"
direction = "Down"

[[]]
click_time = 44.966235708
speed = "Slow"
direction = "Left"

[[]]
click_time = 45.064473041
speed = "Slow"
direction = "Right"

[[]]
click_time = 45.522915833
speed = "Slow"
direction = "Left"

[[]]
click_time = 45.831221375
speed = "Slow"
direction = "Right"

[[]]
click_time = 46.139630916
speed = "Slow"
direction = "Left"

[[]]
click_time = 46.515503666
speed = "Slow"
direction = "Right"

[[]]
click_time = 46.772868708
speed = "Slow"
direction = "Left"

[[]]
click_time = 47.081361708
speed = "Slow"
direction = "Up"

[[]]
click_time = 47.574395333
speed = "Slow"
direction = "Left"

[[]]
click_time = 48.106235375
speed = "Slow"
direction = "Up"

[[]]
click_time = 48.616917333
speed = "Slow"
direction = "Left"

[[]]
click_time = 49.13143375
speed = "Slow"
direction = "Down"

[[]]
click_time = 49.13143375
speed = "Slow"
direction = "Right"

[[]]
click_time = 50.165925916
speed = "Slow"
direction = "Right"

[[]]
click_time = 50.174292
speed = "Slow"
direction = "Down"
