[[]]
click_time = 1.161528791
speed = "Slow"
direction = "Up"

[[]]
click_time = 1.367463208
speed = "Slow"
direction = "Down"

[[]]
click_time = 1.53400875
speed = "Slow"
direction = "Left"

[[]]
click_time = 1.709185833
speed = "Slow"
direction = "Right"

[[]]
click_time = 1.87588975
speed = "Slow"
direction = "Up"
