name = "Map Maker output"
filename = "akisey-dance.ogg"

[[arrows]]
click_time = 0.7578825419999999
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 1.2567974169999996
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 1.756726584
speed = "Slow"
direction = "Up"
